"""
Integration smoke test: CSV upload → full analytics/ML pipeline → exports.

This test exercises every major stage of the platform without Streamlit.
It uses the synthetic sample data generated by `make sample-data`.

Run:  pytest tests/integration/
Skip: the test is automatically skipped if the sample data file is absent.
      Generate it first with: make sample-data
"""
from __future__ import annotations

import io
import pathlib

import pandas as pd
import pytest

SAMPLE_CSV = pathlib.Path("data/sample/subscriptions_sample.csv")


@pytest.mark.skipif(not SAMPLE_CSV.exists(), reason="sample data not found — run: make sample-data")
def test_full_pipeline_smoke() -> None:
    """End-to-end: file bytes → analytics → ML → forecast → insights → exports."""

    # ── Stage 1: Upload ───────────────────────────────────────────────────────
    from src.ingestion.uploader import UploadEngine

    raw_bytes = SAMPLE_CSV.read_bytes()
    upload_result = UploadEngine().process(io.BytesIO(raw_bytes), SAMPLE_CSV.name)
    raw_df = upload_result.dataframe

    assert upload_result.row_count > 50
    assert "customer_id" in raw_df.columns

    # ── Stage 2: Schema validation ────────────────────────────────────────────
    from src.preprocessing.schema import SchemaValidator

    schema_result = SchemaValidator().validate(raw_df)
    norm_df = schema_result.normalised_df.copy()

    assert "transaction_date" in norm_df.columns
    assert "transaction_amount" in norm_df.columns

    # ── Stage 3: Date parsing ─────────────────────────────────────────────────
    from src.preprocessing.date_parser import DateFormatDetector

    date_result = DateFormatDetector().detect_and_parse(norm_df["transaction_date"])
    norm_df["transaction_date"] = date_result.parsed_series

    assert pd.api.types.is_datetime64_any_dtype(norm_df["transaction_date"])

    # ── Stage 4: Data quality ─────────────────────────────────────────────────
    from src.preprocessing.validator import DataQualityChecker, apply_quality_fixes

    quality_report = DataQualityChecker().run_all_checks(norm_df)
    clean_df = apply_quality_fixes(norm_df, quality_report)

    assert len(clean_df) > 0

    # ── Stage 5: KPI calculation ──────────────────────────────────────────────
    from src.analytics.kpis import KPICalculator

    kpi_ts = KPICalculator().calculate(clean_df)

    assert kpi_ts.snapshot.mrr > 0
    assert kpi_ts.snapshot.active_subscribers > 0
    assert len(kpi_ts.monthly_revenue) >= 2

    # ── Stage 6: Cohort analysis (optional — may raise on thin cohorts) ───────
    from src.analytics.cohort import CohortAnalyzer
    from src.utils.exceptions import InsufficientDataError

    try:
        cohort_result = CohortAnalyzer().build(clean_df)
        assert cohort_result.n_cohorts >= 1
    except InsufficientDataError:
        cohort_result = None  # acceptable on small datasets

    # ── Stage 7: Feature engineering ─────────────────────────────────────────
    from src.feature_engineering.churn_labels import ChurnLabelBuilder
    from src.feature_engineering.rfm import RFMBuilder

    rfm_result = RFMBuilder().build(clean_df)
    churn_result = ChurnLabelBuilder().build(clean_df, churn_window_days=90)

    assert rfm_result.n_customers >= 50
    assert 0.0 <= churn_result.churn_rate <= 1.0

    # ── Stage 8: Feature matrix ───────────────────────────────────────────────
    from src.modeling.features import FeatureMatrixBuilder

    fm = FeatureMatrixBuilder().build(clean_df, churn_window_days=90)

    assert fm.X.shape[0] >= 50
    assert fm.X.shape[1] == len(fm.feature_names)
    assert len(fm.y) == len(fm.X)

    # ── Stage 9: Train/test split ─────────────────────────────────────────────
    from src.modeling.validation import TimeSeriesChurnSplit

    split = TimeSeriesChurnSplit().split(fm.X, fm.y, fm.customer_ids, fm.first_tx_dates)

    assert len(split.X_train) > 0
    assert len(split.X_test) > 0

    # ── Stage 10: Model training + evaluation ─────────────────────────────────
    from src.modeling.churn_model import ChurnModel

    model = ChurnModel()
    model.train(split.X_train, split.y_train)
    metrics = model.evaluate(split.X_test, split.y_test)

    assert 0.0 <= metrics.auc <= 1.0
    assert metrics.n_train == len(split.X_train)
    assert metrics.n_test == len(split.X_test)

    # ── Stage 11: SHAP explainability ────────────────────────────────────────
    from src.modeling.explainability import SHAPExplainer

    shap_result = SHAPExplainer().explain(model.rf, split.X_test)

    assert len(shap_result.feature_importance) == len(fm.feature_names)
    assert "mean_abs_shap" in shap_result.feature_importance.columns

    # ── Stage 12: Churn probabilities ────────────────────────────────────────
    proba = model.predict_proba(fm.X)
    predictions = pd.DataFrame({
        "customer_id": fm.customer_ids.values,
        "churn_probability": proba,
    })

    assert (predictions["churn_probability"] >= 0).all()
    assert (predictions["churn_probability"] <= 1).all()

    # ── Stage 13: CLV modeling ────────────────────────────────────────────────
    from src.modeling.clv import CLVModel

    clv_result = CLVModel().fit_and_predict(fm.rfm_features, fm.churn_label_df)

    assert len(clv_result.clv_per_customer) > 0
    assert clv_result.median_lifetime_days > 0

    # ── Stage 14: Customer segmentation ──────────────────────────────────────
    from src.modeling.segmentation import CustomerSegmenter

    churn_prob_s = pd.Series(proba, index=fm.customer_ids.values)
    segments = CustomerSegmenter().segment(fm.rfm_features, fm.churn_label_df, churn_prob_s)

    assert len(segments) == len(fm.customer_ids)
    assert segments.nunique() >= 1

    # ── Stage 15: Forecasting ─────────────────────────────────────────────────
    from src.forecasting.pipeline import ForecastingPipeline

    forecast_bundle = ForecastingPipeline().run(clean_df, horizon_months=6, backend="statsmodels")

    assert len(forecast_bundle.revenue.forecast) == 6
    assert len(forecast_bundle.subscribers.forecast) == 6

    # ── Stage 16: AI insights ─────────────────────────────────────────────────
    from src.insights.models import InsightData
    from src.insights.template_client import TemplateInsightClient

    insight_data = InsightData(
        kpi_snapshot=kpi_ts.snapshot,
        kpi_ts=kpi_ts,
        churn_label_result=churn_result,
        rfm_result=rfm_result,
        cohort_result=cohort_result,
        model_metrics=metrics,
        shap_result=shap_result,
        segments=segments,
        clv_result=clv_result,
        forecast_bundle=forecast_bundle,
    )
    report = TemplateInsightClient().generate(insight_data)

    assert len(report.health_summary) > 0
    assert len(report.churn_analysis) > 0
    assert report.model_confidence is not None

    # ── Stage 17: CSV exports ─────────────────────────────────────────────────
    from src.export import build_at_risk_csv, build_clv_csv, build_insights_pdf

    at_risk_bytes = build_at_risk_csv(predictions, fm.rfm_features)
    assert isinstance(at_risk_bytes, bytes) and len(at_risk_bytes) > 0

    clv_bytes = build_clv_csv(clv_result.clv_per_customer)
    assert isinstance(clv_bytes, bytes) and len(clv_bytes) > 0

    # ── Stage 18: PDF export ──────────────────────────────────────────────────
    pdf_bytes = build_insights_pdf(report, "2026-06-25")
    assert pdf_bytes[:4] == b"%PDF"
    assert len(pdf_bytes) > 1000
